[versions]
algosdk = "2.10.0"
clikt = "5.0.3"
junit = "4.13.2"

[libraries]
algosdk = { module = "com.algorand:algosdk", version.ref = "algosdk" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
junit = { module = "junit:junit", version.ref = "junit" }
