#!/bin/bash

echo "******************************"
echo "  Running git pre-comit hook  "
echo "******************************"

./gradlew ktlingCheck --daemon

RESULT=$?

[ $RESULT -ne 0 ] && exit 1
exit 0