name: "Regression Checks"

on:

  # no timezone support so cron runs in UTC time for now
  schedule:
    - cron: "8 15 * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

  workflow_call:

  push:

jobs:

  disney-scenic-rides:
    name: "Disney Scenic Rides"
    uses: michaeltchuang/a-day-in-my-bobalife/.github/workflows/app-tests.yml@main
    with:
        app_workspace: "DisneyScenicRides"