name: "Regression Check"

on:

  # no timezone support so cron runs in UTC time for now
  schedule:
    - cron: "8 15 * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

  workflow_call:

  push:

  pull-request:

jobs:

  have-a-magical-day:
    name: "Have a magical day"
    uses: michaeltchuang/.github/.github/workflows/clikt-app-tests.yml@main
    with:
        app_workspace: "HaveAMagicalDay"

  disney-scenic-rides:
    name: "Disney Scenic Rides"
    uses: michaeltchuang/.github/.github/workflows/android-app-tests.yml@main
    with:
        app_workspace: "DisneyScenicRides"

  automerge-dependabot:
    name: "Save PR Number for Dependabot Automerge"
    needs: [ have-a-magical-day, disney-scenic-rides ]
    uses: michaeltchuang/.github/.github/workflows/dependabot-save-pr-number.yml@main
    secrets: inherit
